# -*- coding: utf-8 -*-
"""Appends step-10 strings (Settings tab & its screens) to values-XX/strings.xml. Long FAQ/legal text stays English. Run from project root."""
import re
KEYS = ["theme_system","theme_light","theme_dark","file_manager","section_general","app_theme","feedback_or_suggestion",
        "add_widget","explore_more_apps","terms_of_use","privacy_policy","manage_subscriptions","go_to_google_play",
        "ask_every_time","remove_ads","unlock_premium","faq_view_edit","faq_manage","faq_about_app","faq_thanks",
        "rate_our_app","what_problems","add_screenshot","submit","fb_cant_open","fb_too_many_ads","fb_slow","fb_crashes","fb_others"]
T = {
"ar": ["افتراضي النظام","فاتح","داكن","مدير الملفات","عام","مظهر التطبيق","ملاحظات أو اقتراحات","إضافة أداة","استكشف المزيد من التطبيقات","شروط الاستخدام","سياسة الخصوصية","إدارة الاشتراكات","الانتقال إلى Google Play","اسأل في كل مرة","إزالة الإعلانات","افتح جميع الميزات المميزة","العرض والتعديل","إدارة الملفات","حول التطبيق","شكرًا على ملاحظاتك!","قيّم تطبيقنا","ما المشكلات التي واجهتها؟","إضافة لقطة شاشة","إرسال","لا يمكن فتح الملف","إعلانات كثيرة جدًا","بطيء","يتعطل","أخرى"],
"de": ["Systemstandard","Hell","Dunkel","Dateimanager","Allgemein","App-Design","Feedback oder Vorschlag","Widget hinzufügen","Weitere Apps entdecken","Nutzungsbedingungen","Datenschutzerklärung","Abos verwalten","Zu Google Play","Jedes Mal fragen","Werbung entfernen","Alle Premium-Funktionen freischalten","Ansehen & Bearbeiten","Dateien verwalten","Über die App","Danke für dein Feedback!","Bewerte unsere App","Welche Probleme hattest du?","Screenshot hinzufügen","Senden","Datei lässt sich nicht öffnen","Zu viel Werbung","Langsam","Abstürze","Sonstiges"],
"es": ["Predeterminado del sistema","Claro","Oscuro","Administrador de archivos","General","Tema de la app","Comentarios o sugerencias","Añadir widget","Descubre más apps","Términos de uso","Política de privacidad","Gestionar suscripciones","Ir a Google Play","Preguntar siempre","Quitar anuncios","Desbloquea todas las funciones premium","Ver y editar","Gestionar archivos","Acerca de la app","¡Gracias por tus comentarios!","Valora nuestra app","¿Qué problemas encontraste?","Añadir captura","Enviar","No se abre el archivo","Demasiados anuncios","Lenta","Se cierra","Otros"],
"fa": ["پیش‌فرض سیستم","روشن","تیره","مدیر فایل","عمومی","پوسته برنامه","بازخورد یا پیشنهاد","افزودن ابزارک","برنامه‌های بیشتر","شرایط استفاده","سیاست حفظ حریم خصوصی","مدیریت اشتراک‌ها","رفتن به Google Play","هر بار بپرس","حذف تبلیغات","باز کردن همه ویژگی‌های ویژه","مشاهده و ویرایش","مدیریت فایل‌ها","درباره برنامه","از بازخورد شما متشکریم!","به برنامه ما امتیاز دهید","با چه مشکلاتی روبه‌رو شدید؟","افزودن اسکرین‌شات","ارسال","فایل باز نمی‌شود","تبلیغات زیاد","کند","از کار می‌افتد","سایر"],
"fr": ["Par défaut du système","Clair","Sombre","Gestionnaire de fichiers","Général","Thème de l'app","Avis ou suggestion","Ajouter un widget","Découvrir d'autres apps","Conditions d'utilisation","Politique de confidentialité","Gérer les abonnements","Aller sur Google Play","Toujours demander","Supprimer les pubs","Débloquez toutes les fonctions premium","Afficher et modifier","Gérer les fichiers","À propos","Merci pour votre avis !","Notez notre app","Quels problèmes avez-vous rencontrés ?","Ajouter une capture","Envoyer","Impossible d'ouvrir le fichier","Trop de pubs","Lente","Plantages","Autres"],
"in": ["Default sistem","Terang","Gelap","Pengelola file","Umum","Tema aplikasi","Masukan atau saran","Tambah widget","Jelajahi aplikasi lain","Ketentuan penggunaan","Kebijakan privasi","Kelola langganan","Buka Google Play","Selalu tanya","Hapus iklan","Buka semua fitur premium","Lihat & edit","Kelola file","Tentang aplikasi","Terima kasih atas masukan Anda!","Beri nilai aplikasi kami","Masalah apa yang Anda alami?","Tambah tangkapan layar","Kirim","Tidak bisa membuka file","Terlalu banyak iklan","Lambat","Sering berhenti","Lainnya"],
"it": ["Predefinito di sistema","Chiaro","Scuro","File manager","Generali","Tema dell'app","Feedback o suggerimenti","Aggiungi widget","Scopri altre app","Termini di utilizzo","Informativa sulla privacy","Gestisci abbonamenti","Vai a Google Play","Chiedi ogni volta","Rimuovi annunci","Sblocca tutte le funzioni premium","Visualizza e modifica","Gestisci file","Info sull'app","Grazie per il tuo feedback!","Valuta la nostra app","Quali problemi hai riscontrato?","Aggiungi screenshot","Invia","Impossibile aprire il file","Troppi annunci","Lenta","Arresti anomali","Altro"],
"ja": ["システムのデフォルト","ライト","ダーク","ファイルマネージャー","一般","アプリのテーマ","フィードバック・ご提案","ウィジェットを追加","ほかのアプリを見る","利用規約","プライバシーポリシー","定期購入の管理","Google Play へ移動","毎回確認する","広告を削除","すべてのプレミアム機能を解放","表示と編集","ファイル管理","アプリについて","フィードバックありがとうございます！","アプリを評価","どんな問題がありましたか？","スクリーンショットを追加","送信","ファイルを開けない","広告が多すぎる","動作が遅い","クラッシュする","その他"],
"ko": ["시스템 기본값","라이트","다크","파일 관리자","일반","앱 테마","의견 또는 제안","위젯 추가","다른 앱 둘러보기","이용약관","개인정보처리방침","구독 관리","Google Play로 이동","매번 묻기","광고 제거","모든 프리미엄 기능 잠금 해제","보기 및 편집","파일 관리","앱 정보","의견 감사합니다!","앱 평가하기","어떤 문제가 있었나요?","스크린샷 추가","제출","파일을 열 수 없음","광고가 너무 많음","느림","비정상 종료","기타"],
"ms": ["Lalai sistem","Cerah","Gelap","Pengurus fail","Umum","Tema apl","Maklum balas atau cadangan","Tambah widget","Terokai lebih banyak apl","Terma penggunaan","Dasar privasi","Urus langganan","Pergi ke Google Play","Tanya setiap kali","Buang iklan","Buka semua ciri premium","Lihat & edit","Urus fail","Perihal apl","Terima kasih atas maklum balas anda!","Nilai apl kami","Apakah masalah yang anda hadapi?","Tambah tangkapan skrin","Hantar","Tidak dapat membuka fail","Terlalu banyak iklan","Perlahan","Ranap","Lain-lain"],
"pt": ["Padrão do sistema","Claro","Escuro","Gerenciador de arquivos","Geral","Tema do app","Feedback ou sugestão","Adicionar widget","Conheça mais apps","Termos de uso","Política de privacidade","Gerenciar assinaturas","Ir para o Google Play","Perguntar sempre","Remover anúncios","Desbloqueie todos os recursos premium","Ver e editar","Gerenciar arquivos","Sobre o app","Obrigado pelo feedback!","Avalie nosso app","Quais problemas você encontrou?","Adicionar captura de tela","Enviar","Não abre o arquivo","Muitos anúncios","Lento","Travamentos","Outros"],
"ru": ["Как в системе","Светлая","Тёмная","Файловый менеджер","Общие","Тема приложения","Отзыв или предложение","Добавить виджет","Другие наши приложения","Условия использования","Политика конфиденциальности","Управление подписками","Перейти в Google Play","Спрашивать каждый раз","Убрать рекламу","Откройте все премиум-функции","Просмотр и редактирование","Управление файлами","О приложении","Спасибо за отзыв!","Оцените приложение","С какими проблемами вы столкнулись?","Добавить скриншот","Отправить","Не открывается файл","Слишком много рекламы","Медленно","Вылетает","Другое"],
"tr": ["Sistem varsayılanı","Açık","Koyu","Dosya yöneticisi","Genel","Uygulama teması","Geri bildirim veya öneri","Widget ekle","Diğer uygulamaları keşfet","Kullanım koşulları","Gizlilik politikası","Abonelikleri yönet","Google Play'e git","Her seferinde sor","Reklamları kaldır","Tüm premium özelliklerin kilidini açın","Görüntüle ve düzenle","Dosyaları yönet","Uygulama hakkında","Geri bildiriminiz için teşekkürler!","Uygulamamızı puanlayın","Hangi sorunlarla karşılaştınız?","Ekran görüntüsü ekle","Gönder","Dosya açılmıyor","Çok fazla reklam","Yavaş","Çöküyor","Diğer"],
"vi": ["Theo hệ thống","Sáng","Tối","Trình quản lý tệp","Chung","Giao diện ứng dụng","Góp ý hoặc đề xuất","Thêm tiện ích","Khám phá thêm ứng dụng","Điều khoản sử dụng","Chính sách quyền riêng tư","Quản lý gói đăng ký","Đến Google Play","Luôn hỏi","Xóa quảng cáo","Mở khóa mọi tính năng cao cấp","Xem & sửa","Quản lý tệp","Giới thiệu","Cảm ơn góp ý của bạn!","Đánh giá ứng dụng","Bạn gặp vấn đề gì?","Thêm ảnh chụp màn hình","Gửi","Không mở được tệp","Quá nhiều quảng cáo","Chậm","Bị treo","Khác"],
"uz": ["Tizim bo'yicha","Yorug'","Qorong'i","Fayl menejeri","Umumiy","Ilova mavzusi","Fikr yoki taklif","Vidjet qo'shish","Boshqa ilovalar","Foydalanish shartlari","Maxfiylik siyosati","Obunalarni boshqarish","Google Play'ga o'tish","Har safar so'rash","Reklamani olib tashlash","Barcha premium funksiyalarni oching","Ko'rish va tahrirlash","Fayllarni boshqarish","Ilova haqida","Fikringiz uchun rahmat!","Ilovani baholang","Qanday muammolarga duch keldingiz?","Skrinshot qo'shish","Yuborish","Fayl ochilmayapti","Reklama juda ko'p","Sekin","Ishdan chiqadi","Boshqalar"],
"th": ["ตามระบบ","สว่าง","มืด","ตัวจัดการไฟล์","ทั่วไป","ธีมแอป","ความคิดเห็นหรือข้อเสนอแนะ","เพิ่มวิดเจ็ต","สำรวจแอปอื่นๆ","ข้อกำหนดการใช้งาน","นโยบายความเป็นส่วนตัว","จัดการการสมัครสมาชิก","ไปที่ Google Play","ถามทุกครั้ง","ลบโฆษณา","ปลดล็อกฟีเจอร์พรีเมียมทั้งหมด","ดูและแก้ไข","จัดการไฟล์","เกี่ยวกับแอป","ขอบคุณสำหรับความคิดเห็น!","ให้คะแนนแอปของเรา","คุณพบปัญหาอะไรบ้าง?","เพิ่มภาพหน้าจอ","ส่ง","เปิดไฟล์ไม่ได้","โฆษณาเยอะเกินไป","ช้า","แอปค้าง","อื่นๆ"],
"uk": ["Як у системі","Світла","Темна","Файловий менеджер","Загальні","Тема застосунку","Відгук або пропозиція","Додати віджет","Інші наші застосунки","Умови використання","Політика конфіденційності","Керування підписками","Перейти в Google Play","Питати щоразу","Прибрати рекламу","Відкрийте всі преміум-функції","Перегляд і редагування","Керування файлами","Про застосунок","Дякуємо за відгук!","Оцініть застосунок","З якими проблемами ви зіткнулися?","Додати знімок екрана","Надіслати","Файл не відкривається","Забагато реклами","Повільно","Вилітає","Інше"],
"pl": ["Domyślny systemu","Jasny","Ciemny","Menedżer plików","Ogólne","Motyw aplikacji","Opinia lub sugestia","Dodaj widżet","Poznaj inne aplikacje","Warunki korzystania","Polityka prywatności","Zarządzaj subskrypcjami","Przejdź do Google Play","Pytaj za każdym razem","Usuń reklamy","Odblokuj wszystkie funkcje premium","Przeglądanie i edycja","Zarządzanie plikami","O aplikacji","Dziękujemy za opinię!","Oceń naszą aplikację","Jakie problemy napotkałeś?","Dodaj zrzut ekranu","Wyślij","Nie można otworzyć pliku","Za dużo reklam","Wolno działa","Awarie","Inne"],
"tl": ["Default ng system","Maliwanag","Madilim","File manager","Pangkalahatan","Tema ng app","Feedback o mungkahi","Magdagdag ng widget","Tuklasin ang iba pang app","Mga tuntunin ng paggamit","Patakaran sa privacy","Pamahalaan ang subscription","Pumunta sa Google Play","Laging itanong","Alisin ang mga ad","I-unlock ang lahat ng premium feature","Tingnan at i-edit","Pamahalaan ang mga file","Tungkol sa app","Salamat sa iyong feedback!","I-rate ang aming app","Anong problema ang naranasan mo?","Magdagdag ng screenshot","Isumite","Hindi mabuksan ang file","Masyadong maraming ad","Mabagal","Nagka-crash","Iba pa"],
"zh-rTW": ["跟隨系統","淺色","深色","檔案管理員","一般","應用程式主題","意見回饋或建議","新增小工具","探索更多應用程式","使用條款","隱私權政策","管理訂閱","前往 Google Play","每次都詢問","移除廣告","解鎖所有進階功能","檢視與編輯","管理檔案","關於應用程式","感謝您的回饋！","為我們的應用程式評分","您遇到了什麼問題？","新增螢幕截圖","提交","無法開啟檔案","廣告太多","速度慢","當機","其他"],
"ur": ["سسٹم ڈیفالٹ","ہلکا","گہرا","فائل مینیجر","عمومی","ایپ تھیم","رائے یا تجویز","ویجیٹ شامل کریں","مزید ایپس دیکھیں","استعمال کی شرائط","رازداری کی پالیسی","سبسکرپشنز کا انتظام","Google Play پر جائیں","ہر بار پوچھیں","اشتہارات ہٹائیں","تمام پریمیم خصوصیات کھولیں","دیکھیں اور ترمیم کریں","فائلوں کا انتظام","ایپ کے بارے میں","آپ کی رائے کا شکریہ!","ہماری ایپ کو ریٹ کریں","آپ کو کن مسائل کا سامنا ہوا؟","اسکرین شاٹ شامل کریں","جمع کرائیں","فائل نہیں کھلتی","بہت زیادہ اشتہارات","سست","کریش ہوتی ہے","دیگر"],
"zh-rCN": ["跟随系统","浅色","深色","文件管理器","通用","应用主题","反馈或建议","添加小部件","探索更多应用","使用条款","隐私政策","管理订阅","前往 Google Play","每次都询问","移除广告","解锁全部高级功能","查看与编辑","管理文件","关于应用","感谢你的反馈！","为我们的应用评分","你遇到了什么问题？","添加截图","提交","无法打开文件","广告太多","速度慢","闪退","其他"],
}
def esc(s):
    return s.replace("&", "&amp;").replace("'", "\\'").replace('"', '\\"')
for loc, vals in T.items():
    assert len(vals) == len(KEYS), (loc, len(vals))
    p = f"app/src/main/res/values-{loc}/strings.xml"
    s = open(p, encoding="utf-8").read()
    s = re.sub(r"\n    <!-- step10 -->.*?<!-- /step10 -->", "", s, flags=re.S)
    block = "\n    <!-- step10 -->\n" + "".join(f'    <string name="{k}">{esc(v)}</string>\n' for k, v in zip(KEYS, vals)) + "    <!-- /step10 -->"
    s = s.replace("\n</resources>", block + "\n</resources>")
    open(p, "w", encoding="utf-8").write(s)
print("step10 translations:", len(T))
