# -*- coding: utf-8 -*-
"""Appends step-3 strings (Directories, viewer, pages) to values-XX/strings.xml. Run from project root."""
import re
KEYS = ["storage","all_documents","recycle_bin","recently_added","restore","delete_permanently","empty_recycle_bin",
        "unsupported_title","loading","saved_successfully","pages","bookmark","mode_vertical","mode_horizontal","rotate",
        "search","invert","go_to_page","jump_tip","drag_hint","insert","extract","blank_pages","images","delete_confirm",
        "deleted_successfully","insert_blank_pages","page_size","page_color","orientation","page_count","follow_previous","apply"]
T = {
"ar": ["التخزين","كل المستندات","سلة المحذوفات","المضافة حديثًا","استعادة","حذف نهائي","إفراغ السلة","نوع الملف غير مدعوم","جارٍ التحميل…","تم الحفظ بنجاح","الصفحات","إشارة مرجعية","عمودي","أفقي","تدوير","بحث","عكس الألوان","الانتقال إلى صفحة","اضغط هنا للانتقال إلى الصفحة مباشرة","اضغط مطولًا واسحب لإعادة الترتيب","إدراج","استخراج","صفحات فارغة","صور","تأكيد الحذف","تم الحذف بنجاح","إدراج صفحات فارغة","حجم الصفحة","لون الصفحة","الاتجاه","عدد الصفحات","مثل السابقة","تطبيق"],
"de": ["Speicher","Alle Dokumente","Papierkorb","Kürzlich hinzugefügt","Wiederherstellen","Endgültig löschen","Papierkorb leeren","Dateityp nicht unterstützt","Wird geladen…","Erfolgreich gespeichert","Seiten","Lesezeichen","Vertikal","Horizontal","Drehen","Suchen","Invertieren","Gehe zu Seite","Tippe hier, um direkt zur Seite zu springen","Lange drücken und ziehen zum Sortieren","Einfügen","Extrahieren","Leere Seiten","Bilder","Löschen bestätigen","Erfolgreich gelöscht","Leere Seiten einfügen","Seitengröße","Seitenfarbe","Ausrichtung","Seitenanzahl","Wie vorherige","Anwenden"],
"es": ["Almacenamiento","Todos los documentos","Papelera","Añadidos recientemente","Restaurar","Eliminar definitivamente","Vaciar papelera","Tipo de archivo no compatible","Cargando…","Guardado correctamente","Páginas","Marcador","Vertical","Horizontal","Girar","Buscar","Invertir","Ir a la página","Toca aquí para ir directamente a la página","Mantén pulsado y arrastra para reordenar","Insertar","Extraer","Páginas en blanco","Imágenes","Confirmar eliminación","Eliminado correctamente","Insertar páginas en blanco","Tamaño de página","Color de página","Orientación","Número de páginas","Igual que la anterior","Aplicar"],
"fa": ["حافظه","همه اسناد","سطل بازیافت","اخیراً اضافه‌شده","بازیابی","حذف دائمی","خالی کردن سطل","نوع فایل پشتیبانی نمی‌شود","در حال بارگیری…","با موفقیت ذخیره شد","صفحات","نشانک","عمودی","افقی","چرخش","جستجو","معکوس رنگ","رفتن به صفحه","برای رفتن مستقیم به صفحه اینجا ضربه بزنید","برای جابه‌جایی نگه دارید و بکشید","درج","استخراج","صفحات خالی","تصاویر","تأیید حذف","با موفقیت حذف شد","درج صفحات خالی","اندازه صفحه","رنگ صفحه","جهت","تعداد صفحات","مانند قبلی","اعمال"],
"fr": ["Stockage","Tous les documents","Corbeille","Ajoutés récemment","Restaurer","Supprimer définitivement","Vider la corbeille","Type de fichier non pris en charge","Chargement…","Enregistré avec succès","Pages","Favori","Vertical","Horizontal","Pivoter","Rechercher","Inverser","Aller à la page","Touchez ici pour aller directement à la page","Appui long et glisser pour réorganiser","Insérer","Extraire","Pages vierges","Images","Confirmer la suppression","Supprimé avec succès","Insérer des pages vierges","Taille de page","Couleur de page","Orientation","Nombre de pages","Comme la précédente","Appliquer"],
"in": ["Penyimpanan","Semua dokumen","Sampah","Baru ditambahkan","Pulihkan","Hapus permanen","Kosongkan sampah","Jenis file tidak didukung","Memuat…","Berhasil disimpan","Halaman","Bookmark","Vertikal","Horizontal","Putar","Cari","Balik warna","Ke halaman","Ketuk di sini untuk langsung ke halaman","Tekan lama dan seret untuk mengurutkan","Sisipkan","Ekstrak","Halaman kosong","Gambar","Konfirmasi hapus","Berhasil dihapus","Sisipkan halaman kosong","Ukuran halaman","Warna halaman","Orientasi","Jumlah halaman","Ikuti sebelumnya","Terapkan"],
"it": ["Memoria","Tutti i documenti","Cestino","Aggiunti di recente","Ripristina","Elimina definitivamente","Svuota cestino","Tipo di file non supportato","Caricamento…","Salvato correttamente","Pagine","Segnalibro","Verticale","Orizzontale","Ruota","Cerca","Inverti","Vai alla pagina","Tocca qui per andare direttamente alla pagina","Tieni premuto e trascina per riordinare","Inserisci","Estrai","Pagine vuote","Immagini","Conferma eliminazione","Eliminato correttamente","Inserisci pagine vuote","Formato pagina","Colore pagina","Orientamento","Numero di pagine","Come la precedente","Applica"],
"ja": ["ストレージ","すべてのドキュメント","ごみ箱","最近追加","復元","完全に削除","ごみ箱を空にする","このファイル形式には対応していません","読み込み中…","保存しました","ページ","ブックマーク","縦","横","回転","検索","反転","ページへ移動","ここをタップしてページに直接移動","長押ししてドラッグで並べ替え","挿入","抽出","白紙ページ","画像","削除の確認","削除しました","白紙ページを挿入","ページサイズ","ページの色","向き","ページ数","前のページと同じ","適用"],
"ko": ["저장공간","모든 문서","휴지통","최근 추가됨","복원","영구 삭제","휴지통 비우기","지원되지 않는 파일 형식","불러오는 중…","저장되었습니다","페이지","북마크","세로","가로","회전","검색","색상 반전","페이지로 이동","여기를 눌러 페이지로 바로 이동","길게 눌러 끌어서 순서 변경","삽입","추출","빈 페이지","이미지","삭제 확인","삭제되었습니다","빈 페이지 삽입","페이지 크기","페이지 색상","방향","페이지 수","이전과 동일","적용"],
"ms": ["Storan","Semua dokumen","Tong kitar semula","Baru ditambah","Pulihkan","Padam kekal","Kosongkan tong","Jenis fail tidak disokong","Memuatkan…","Berjaya disimpan","Halaman","Penanda buku","Menegak","Mendatar","Putar","Cari","Songsang","Pergi ke halaman","Ketik di sini untuk terus ke halaman","Tekan lama dan seret untuk susun semula","Sisip","Ekstrak","Halaman kosong","Imej","Sahkan padam","Berjaya dipadam","Sisip halaman kosong","Saiz halaman","Warna halaman","Orientasi","Bilangan halaman","Ikut sebelumnya","Guna"],
"pt": ["Armazenamento","Todos os documentos","Lixeira","Adicionados recentemente","Restaurar","Excluir permanentemente","Esvaziar lixeira","Tipo de arquivo não suportado","Carregando…","Salvo com sucesso","Páginas","Favorito","Vertical","Horizontal","Girar","Pesquisar","Inverter","Ir para a página","Toque aqui para ir direto à página","Toque e segure e arraste para reordenar","Inserir","Extrair","Páginas em branco","Imagens","Confirmar exclusão","Excluído com sucesso","Inserir páginas em branco","Tamanho da página","Cor da página","Orientação","Número de páginas","Igual à anterior","Aplicar"],
"ru": ["Хранилище","Все документы","Корзина","Недавно добавленные","Восстановить","Удалить навсегда","Очистить корзину","Тип файла не поддерживается","Загрузка…","Успешно сохранено","Страницы","Закладка","Вертикально","Горизонтально","Повернуть","Поиск","Инверсия","Перейти к странице","Нажмите, чтобы сразу перейти к странице","Удерживайте и перетаскивайте для сортировки","Вставить","Извлечь","Пустые страницы","Изображения","Подтвердите удаление","Успешно удалено","Вставить пустые страницы","Размер страницы","Цвет страницы","Ориентация","Количество страниц","Как предыдущая","Применить"],
"tr": ["Depolama","Tüm belgeler","Geri dönüşüm kutusu","Son eklenenler","Geri yükle","Kalıcı olarak sil","Kutuyu boşalt","Dosya türü desteklenmiyor","Yükleniyor…","Başarıyla kaydedildi","Sayfalar","Yer imi","Dikey","Yatay","Döndür","Ara","Renkleri ters çevir","Sayfaya git","Doğrudan sayfaya gitmek için dokunun","Sıralamak için basılı tutup sürükleyin","Ekle","Çıkar","Boş sayfalar","Resimler","Silmeyi onayla","Başarıyla silindi","Boş sayfa ekle","Sayfa boyutu","Sayfa rengi","Yön","Sayfa sayısı","Öncekiyle aynı","Uygula"],
"vi": ["Bộ nhớ","Tất cả tài liệu","Thùng rác","Mới thêm gần đây","Khôi phục","Xóa vĩnh viễn","Dọn thùng rác","Không hỗ trợ loại tệp này","Đang tải…","Đã lưu thành công","Trang","Dấu trang","Dọc","Ngang","Xoay","Tìm kiếm","Đảo màu","Đi tới trang","Nhấn vào đây để đi thẳng tới trang","Nhấn giữ và kéo để sắp xếp","Chèn","Trích xuất","Trang trống","Hình ảnh","Xác nhận xóa","Đã xóa thành công","Chèn trang trống","Khổ giấy","Màu trang","Hướng","Số trang","Giống trang trước","Áp dụng"],
"uz": ["Xotira","Barcha hujjatlar","Savat","Yaqinda qo\\'shilgan","Tiklash","Butunlay o\\'chirish","Savatni tozalash","Fayl turi qo\\'llab-quvvatlanmaydi","Yuklanmoqda…","Muvaffaqiyatli saqlandi","Sahifalar","Xatcho\\'p","Vertikal","Gorizontal","Aylantirish","Qidirish","Ranglarni teskari","Sahifaga o\\'tish","Sahifaga to\\'g\\'ridan-to\\'g\\'ri o\\'tish uchun bosing","Tartiblash uchun bosib turib suring","Qo\\'shish","Ajratib olish","Bo\\'sh sahifalar","Rasmlar","O\\'chirishni tasdiqlang","Muvaffaqiyatli o\\'chirildi","Bo\\'sh sahifa qo\\'shish","Sahifa o\\'lchami","Sahifa rangi","Yo\\'nalish","Sahifalar soni","Oldingidek","Qo\\'llash"],
"th": ["ที่จัดเก็บ","เอกสารทั้งหมด","ถังขยะ","เพิ่มล่าสุด","กู้คืน","ลบถาวร","ล้างถังขยะ","ไม่รองรับไฟล์ประเภทนี้","กำลังโหลด…","บันทึกสำเร็จ","หน้า","บุ๊กมาร์ก","แนวตั้ง","แนวนอน","หมุน","ค้นหา","กลับสี","ไปที่หน้า","แตะที่นี่เพื่อไปที่หน้าโดยตรง","กดค้างแล้วลากเพื่อจัดเรียง","แทรก","แยกหน้า","หน้าว่าง","รูปภาพ","ยืนยันการลบ","ลบสำเร็จ","แทรกหน้าว่าง","ขนาดหน้า","สีหน้า","การวางแนว","จำนวนหน้า","ตามหน้าก่อน","ใช้"],
"uk": ["Сховище","Усі документи","Кошик","Нещодавно додані","Відновити","Видалити назавжди","Очистити кошик","Тип файлу не підтримується","Завантаження…","Успішно збережено","Сторінки","Закладка","Вертикально","Горизонтально","Повернути","Пошук","Інверсія","Перейти до сторінки","Торкніться, щоб одразу перейти до сторінки","Утримуйте й перетягуйте для сортування","Вставити","Витягти","Порожні сторінки","Зображення","Підтвердьте видалення","Успішно видалено","Вставити порожні сторінки","Розмір сторінки","Колір сторінки","Орієнтація","Кількість сторінок","Як попередня","Застосувати"],
"pl": ["Pamięć","Wszystkie dokumenty","Kosz","Ostatnio dodane","Przywróć","Usuń trwale","Opróżnij kosz","Nieobsługiwany typ pliku","Wczytywanie…","Zapisano pomyślnie","Strony","Zakładka","Pionowo","Poziomo","Obróć","Szukaj","Odwróć kolory","Przejdź do strony","Dotknij, aby przejść bezpośrednio do strony","Przytrzymaj i przeciągnij, aby zmienić kolejność","Wstaw","Wyodrębnij","Puste strony","Obrazy","Potwierdź usunięcie","Usunięto pomyślnie","Wstaw puste strony","Rozmiar strony","Kolor strony","Orientacja","Liczba stron","Jak poprzednia","Zastosuj"],
"tl": ["Storage","Lahat ng dokumento","Recycle bin","Bagong idinagdag","Ibalik","Burahin nang tuluyan","Alisan ng laman","Hindi suportado ang uri ng file","Naglo-load…","Matagumpay na na-save","Mga pahina","Bookmark","Patayo","Pahalang","I-rotate","Maghanap","I-invert","Pumunta sa pahina","I-tap dito para direktang pumunta sa pahina","Pindutin nang matagal at i-drag para ayusin","Magsingit","I-extract","Mga blangkong pahina","Mga larawan","Kumpirmahin ang pagbura","Matagumpay na nabura","Magsingit ng blangkong pahina","Laki ng pahina","Kulay ng pahina","Oryentasyon","Bilang ng pahina","Gaya ng nauna","Ilapat"],
"zh-rTW": ["儲存空間","所有文件","資源回收筒","最近新增","還原","永久刪除","清空回收筒","不支援此檔案類型","載入中…","已成功儲存","頁面","書籤","垂直","水平","旋轉","搜尋","反轉色彩","跳至頁面","點選這裡可直接跳至頁面","長按並拖曳以重新排序","插入","擷取","空白頁","圖片","確認刪除","已成功刪除","插入空白頁","頁面大小","頁面顏色","方向","頁數","與前一頁相同","套用"],
"ur": ["اسٹوریج","تمام دستاویزات","ری سائیکل بن","حال ہی میں شامل","بحال کریں","مستقل حذف کریں","بن خالی کریں","فائل کی قسم معاون نہیں","لوڈ ہو رہا ہے…","کامیابی سے محفوظ ہو گیا","صفحات","بُک مارک","عمودی","افقی","گھمائیں","تلاش","رنگ الٹیں","صفحے پر جائیں","صفحے پر براہ راست جانے کے لیے یہاں ٹیپ کریں","ترتیب بدلنے کے لیے دبا کر گھسیٹیں","شامل کریں","نکالیں","خالی صفحات","تصاویر","حذف کی تصدیق","کامیابی سے حذف ہو گیا","خالی صفحات شامل کریں","صفحے کا سائز","صفحے کا رنگ","سمت","صفحات کی تعداد","پچھلے جیسا","لاگو کریں"],
"zh-rCN": ["存储","所有文档","回收站","最近添加","恢复","永久删除","清空回收站","不支持此文件类型","加载中…","保存成功","页面","书签","纵向","横向","旋转","搜索","反色","跳转到页面","点击这里可直接跳转到页面","长按并拖动以重新排序","插入","提取","空白页","图片","确认删除","删除成功","插入空白页","页面大小","页面颜色","方向","页数","与上一页相同","应用"],
}
def esc(s):
    out = s.replace("\\'", "\u0000").replace("'", "\\'").replace('"', '\\"')
    return out.replace("\u0000", "\\'")
for loc, vals in T.items():
    assert len(vals) == len(KEYS), (loc, len(vals))
    p = f"app/src/main/res/values-{loc}/strings.xml"
    s = open(p, encoding="utf-8").read()
    s = re.sub(r"\n    <!-- step3 -->.*?<!-- /step3 -->", "", s, flags=re.S)
    block = "\n    <!-- step3 -->\n" + "".join(f'    <string name="{k}">{esc(v)}</string>\n' for k, v in zip(KEYS, vals)) + "    <!-- /step3 -->"
    s = s.replace("\n</resources>", block + "\n</resources>")
    open(p, "w", encoding="utf-8").write(s)
print("step3 translations:", len(T))
