# -*- coding: utf-8 -*-
"""Appends step-9 strings (Tools tab, PDF editor) to values-XX/strings.xml. Run from project root."""
import re
KEYS = ["section_convert_create","section_edit","section_others","manage_pages","feature_request","tell_us","add_image",
        "tap_anywhere_add_text","tap_text_to_edit","no_editable_text","enter_text","clear","color","size","add_signature",
        "sign_here","edit_pdf","tut_edit_title","tut_sign_title","try_now","later"]
T = {
"ar": ["تحويل وإنشاء","تعديل","أخرى","إدارة الصفحات","لا تجد الميزة التي تريدها؟","أخبرنا","إضافة صورة","اضغط في أي مكان لإضافة نص","اضغط على النص الذي تريد تعديله","لا يحتوي ملف PDF هذا على نص قابل للتعديل (صفحات ممسوحة). استخدم إضافة نص.","أدخل النص","مسح","اللون","الحجم","+  إضافة توقيع","وقّع هنا","تعديل PDF","عدّل ملفات PDF بسهولة.","وقّع المستندات في ثوانٍ.","جرّب الآن","لاحقًا"],
"de": ["Konvertieren & Erstellen","Bearbeiten","Sonstiges","Seiten verwalten","Fehlt dir eine Funktion?","Sag es uns","Bild hinzufügen","Tippe irgendwo, um Text hinzuzufügen","Tippe auf den Text, den du bearbeiten möchtest","Dieses PDF enthält keinen bearbeitbaren Text (gescannte Seiten). Nutze Text hinzufügen.","Text eingeben","Löschen","Farbe","Größe","+  Unterschrift hinzufügen","Hier unterschreiben","PDF bearbeiten","PDFs ganz einfach bearbeiten.","Dokumente in Sekunden unterschreiben.","Jetzt testen","Später"],
"es": ["Convertir y crear","Editar","Otros","Gestionar páginas","¿No encuentras la función que quieres?","Dínoslo","Añadir imagen","Toca en cualquier lugar para añadir texto","Toca el texto que quieres editar","Este PDF no tiene texto editable (páginas escaneadas). Usa Añadir texto.","Escribe el texto","Borrar","Color","Tamaño","+  Añadir firma","Firma aquí","Editar PDF","Edita PDF fácilmente.","Firma documentos en segundos.","Probar ahora","Más tarde"],
"fa": ["تبدیل و ایجاد","ویرایش","سایر","مدیریت صفحات","ویژگی مورد نظرتان را ندارید؟","به ما بگویید","افزودن تصویر","برای افزودن متن هر جا ضربه بزنید","روی متنی که می‌خواهید ویرایش کنید ضربه بزنید","این PDF متن قابل ویرایش ندارد (صفحات اسکن‌شده). از افزودن متن استفاده کنید.","متن را وارد کنید","پاک کردن","رنگ","اندازه","+  افزودن امضا","اینجا امضا کنید","ویرایش PDF","PDFها را به‌راحتی ویرایش کنید.","اسناد را در چند ثانیه امضا کنید.","امتحان کنید","بعداً"],
"fr": ["Convertir et créer","Modifier","Autres","Gérer les pages","Il vous manque une fonction ?","Dites-le-nous","Ajouter une image","Touchez n'importe où pour ajouter du texte","Touchez le texte à modifier","Ce PDF ne contient pas de texte modifiable (pages numérisées). Utilisez Ajouter du texte.","Saisir le texte","Effacer","Couleur","Taille","+  Ajouter une signature","Signez ici","Modifier le PDF","Modifiez vos PDF facilement.","Signez vos documents en quelques secondes.","Essayer","Plus tard"],
"in": ["Konversi & Buat","Edit","Lainnya","Kelola halaman","Tidak menemukan fitur yang Anda inginkan?","Beri tahu kami","Tambah gambar","Ketuk di mana saja untuk menambah teks","Ketuk teks yang ingin diedit","PDF ini tidak memiliki teks yang dapat diedit (halaman hasil pindai). Gunakan Tambah teks.","Masukkan teks","Hapus","Warna","Ukuran","+  Tambah tanda tangan","Tanda tangan di sini","Edit PDF","Edit PDF dengan mudah.","Tanda tangani dokumen dalam hitungan detik.","Coba sekarang","Nanti"],
"it": ["Converti e crea","Modifica","Altro","Gestisci pagine","Non trovi la funzione che cerchi?","Diccelo","Aggiungi immagine","Tocca ovunque per aggiungere testo","Tocca il testo da modificare","Questo PDF non contiene testo modificabile (pagine scansionate). Usa Aggiungi testo.","Inserisci testo","Cancella","Colore","Dimensione","+  Aggiungi firma","Firma qui","Modifica PDF","Modifica i PDF con facilità.","Firma documenti in pochi secondi.","Prova ora","Più tardi"],
"ja": ["変換と作成","編集","その他","ページ管理","欲しい機能がありませんか？","お知らせください","画像を追加","タップしてテキストを追加","編集したいテキストをタップ","このPDFには編集できるテキストがありません（スキャンしたページ）。テキストを追加をご利用ください。","テキストを入力","クリア","色","サイズ","+  署名を追加","ここに署名","PDFを編集","PDFをかんたんに編集。","数秒で文書に署名。","今すぐ試す","あとで"],
"ko": ["변환 및 만들기","편집","기타","페이지 관리","원하는 기능이 없나요?","알려 주세요","이미지 추가","아무 곳이나 탭하여 텍스트 추가","편집할 텍스트를 탭하세요","이 PDF에는 편집 가능한 텍스트가 없습니다(스캔한 페이지). 텍스트 추가를 사용하세요.","텍스트 입력","지우기","색상","크기","+  서명 추가","여기에 서명","PDF 편집","PDF를 쉽게 편집하세요.","몇 초 만에 문서에 서명하세요.","지금 사용해 보기","나중에"],
"ms": ["Tukar & Cipta","Edit","Lain-lain","Urus halaman","Tiada ciri yang anda mahu?","Beritahu kami","Tambah imej","Ketik di mana-mana untuk menambah teks","Ketik teks yang ingin diedit","PDF ini tiada teks boleh edit (halaman imbasan). Gunakan Tambah teks.","Masukkan teks","Kosongkan","Warna","Saiz","+  Tambah tandatangan","Tandatangan di sini","Edit PDF","Edit PDF dengan mudah.","Tandatangani dokumen dalam beberapa saat.","Cuba sekarang","Kemudian"],
"pt": ["Converter e criar","Editar","Outros","Gerenciar páginas","Não encontrou o recurso que quer?","Conte para nós","Adicionar imagem","Toque em qualquer lugar para adicionar texto","Toque no texto que quer editar","Este PDF não tem texto editável (páginas digitalizadas). Use Adicionar texto.","Digite o texto","Limpar","Cor","Tamanho","+  Adicionar assinatura","Assine aqui","Editar PDF","Edite PDFs com facilidade.","Assine documentos em segundos.","Experimentar","Depois"],
"ru": ["Конвертация и создание","Редактирование","Другое","Управление страницами","Не нашли нужную функцию?","Сообщите нам","Добавить изображение","Нажмите в любом месте, чтобы добавить текст","Нажмите на текст, который хотите изменить","В этом PDF нет редактируемого текста (сканы). Используйте «Добавить текст».","Введите текст","Очистить","Цвет","Размер","+  Добавить подпись","Подпишите здесь","Редактировать PDF","Редактируйте PDF легко.","Подписывайте документы за секунды.","Попробовать","Позже"],
"tr": ["Dönüştür ve Oluştur","Düzenle","Diğer","Sayfaları yönet","İstediğiniz özellik yok mu?","Bize söyleyin","Resim ekle","Metin eklemek için herhangi bir yere dokunun","Düzenlemek istediğiniz metne dokunun","Bu PDF'de düzenlenebilir metin yok (taranmış sayfalar). Metin ekle'yi kullanın.","Metin girin","Temizle","Renk","Boyut","+  İmza ekle","Buraya imzalayın","PDF'yi düzenle","PDF'leri kolayca düzenleyin.","Belgeleri saniyeler içinde imzalayın.","Şimdi dene","Sonra"],
"vi": ["Chuyển đổi & Tạo","Chỉnh sửa","Khác","Quản lý trang","Không có tính năng bạn cần?","Cho chúng tôi biết","Thêm hình ảnh","Chạm vào bất kỳ đâu để thêm văn bản","Chạm vào văn bản muốn sửa","PDF này không có văn bản sửa được (trang quét). Hãy dùng Thêm văn bản.","Nhập văn bản","Xóa","Màu","Cỡ","+  Thêm chữ ký","Ký tại đây","Sửa PDF","Chỉnh sửa PDF dễ dàng.","Ký tài liệu chỉ trong vài giây.","Thử ngay","Để sau"],
"uz": ["Aylantirish va yaratish","Tahrirlash","Boshqalar","Sahifalarni boshqarish","Kerakli funksiya yo\\'qmi?","Bizga ayting","Rasm qo\\'shish","Matn qo\\'shish uchun istalgan joyga bosing","Tahrirlamoqchi bo\\'lgan matnga bosing","Bu PDF-da tahrirlanadigan matn yo\\'q (skaner sahifalar). Matn qo\\'shishdan foydalaning.","Matn kiriting","Tozalash","Rang","O\\'lcham","+  Imzo qo\\'shish","Shu yerga imzo qo\\'ying","PDF tahrirlash","PDF-larni oson tahrirlang.","Hujjatlarni soniyalarda imzolang.","Hozir sinash","Keyinroq"],
"th": ["แปลงและสร้าง","แก้ไข","อื่นๆ","จัดการหน้า","ไม่มีฟีเจอร์ที่คุณต้องการ?","บอกเรา","เพิ่มรูปภาพ","แตะที่ใดก็ได้เพื่อเพิ่มข้อความ","แตะข้อความที่ต้องการแก้ไข","PDF นี้ไม่มีข้อความที่แก้ไขได้ (หน้าสแกน) ใช้เพิ่มข้อความแทน","ป้อนข้อความ","ล้าง","สี","ขนาด","+  เพิ่มลายเซ็น","ลงชื่อที่นี่","แก้ไข PDF","แก้ไข PDF ได้ง่ายๆ","ลงนามเอกสารในไม่กี่วินาที","ลองเลย","ภายหลัง"],
"uk": ["Конвертація і створення","Редагування","Інше","Керування сторінками","Немає потрібної функції?","Повідомте нам","Додати зображення","Торкніться будь-де, щоб додати текст","Торкніться тексту, який хочете змінити","У цьому PDF немає тексту для редагування (скани). Скористайтеся «Додати текст».","Введіть текст","Очистити","Колір","Розмір","+  Додати підпис","Підпишіть тут","Редагувати PDF","Редагуйте PDF легко.","Підписуйте документи за секунди.","Спробувати","Пізніше"],
"pl": ["Konwertuj i twórz","Edytuj","Inne","Zarządzaj stronami","Brakuje Ci funkcji?","Napisz do nas","Dodaj obraz","Dotknij w dowolnym miejscu, aby dodać tekst","Dotknij tekstu, który chcesz edytować","Ten PDF nie ma edytowalnego tekstu (skany). Użyj Dodaj tekst.","Wpisz tekst","Wyczyść","Kolor","Rozmiar","+  Dodaj podpis","Podpisz tutaj","Edytuj PDF","Łatwa edycja PDF.","Podpisuj dokumenty w kilka sekund.","Wypróbuj","Później"],
"tl": ["I-convert at Gumawa","I-edit","Iba pa","Pamahalaan ang mga pahina","Wala ang feature na gusto mo?","Sabihin sa amin","Magdagdag ng larawan","I-tap kahit saan para magdagdag ng text","I-tap ang text na gusto mong i-edit","Walang nae-edit na text ang PDF na ito (na-scan). Gamitin ang Magdagdag ng text.","Ilagay ang text","I-clear","Kulay","Laki","+  Magdagdag ng pirma","Pumirma dito","I-edit ang PDF","Madaling mag-edit ng PDF.","Pumirma ng dokumento sa ilang segundo.","Subukan ngayon","Mamaya"],
"zh-rTW": ["轉換與建立","編輯","其他","管理頁面","找不到想要的功能？","告訴我們","新增圖片","點一下任意位置以新增文字","點一下要編輯的文字","此 PDF 沒有可編輯的文字（掃描頁面），請使用新增文字。","輸入文字","清除","顏色","大小","+  新增簽名","在此簽名","編輯 PDF","輕鬆編輯 PDF。","幾秒內簽署文件。","立即試用","稍後"],
"ur": ["تبدیل اور تخلیق","ترمیم","دیگر","صفحات کا انتظام","آپ کی مطلوبہ خصوصیت نہیں ہے؟","ہمیں بتائیں","تصویر شامل کریں","متن شامل کرنے کے لیے کہیں بھی ٹیپ کریں","جس متن میں ترمیم کرنی ہے اس پر ٹیپ کریں","اس PDF میں قابلِ ترمیم متن نہیں (اسکین شدہ صفحات)۔ متن شامل کریں استعمال کریں۔","متن درج کریں","صاف کریں","رنگ","سائز","+  دستخط شامل کریں","یہاں دستخط کریں","PDF میں ترمیم","PDF میں آسانی سے ترمیم کریں۔","سیکنڈوں میں دستاویزات پر دستخط کریں۔","ابھی آزمائیں","بعد میں"],
"zh-rCN": ["转换与创建","编辑","其他","管理页面","没有你想要的功能？","告诉我们","添加图片","点按任意位置添加文字","点按要编辑的文字","此 PDF 没有可编辑的文字（扫描页面），请使用添加文字。","输入文字","清除","颜色","大小","+  添加签名","在此签名","编辑 PDF","轻松编辑 PDF。","几秒内签署文件。","立即试用","稍后"],
}
def esc(s):
    out = s.replace("\\'", "\u0000").replace("'", "\\'").replace('"', '\\"')
    return out.replace("\u0000", "\\'")
for loc, vals in T.items():
    assert len(vals) == len(KEYS), (loc, len(vals))
    p = f"app/src/main/res/values-{loc}/strings.xml"
    s = open(p, encoding="utf-8").read()
    s = re.sub(r"\n    <!-- step9 -->.*?<!-- /step9 -->", "", s, flags=re.S)
    block = "\n    <!-- step9 -->\n" + "".join(f'    <string name="{k}">{esc(v).replace("&", "&amp;")}</string>\n' for k, v in zip(KEYS, vals)) + "    <!-- /step9 -->"
    s = s.replace("\n</resources>", block + "\n</resources>")
    open(p, "w", encoding="utf-8").write(s)
print("step9 translations:", len(T))
