# -*- coding: utf-8 -*-
"""Appends step-6 strings (Image to PDF / Scan flow) to values-XX/strings.xml. Run from project root."""
import re
KEYS = ["take_a_photo","choose_from_gallery","choose_cropping_method","crop_method_hint","auto_crop","no_crop","dont_ask_again",
        "scan_settings","camera_permission_needed","capture_failed","retake","crop","left","right","apply_to_all","no_edges_found",
        "processing_progress","add_pages","converted_successfully_excl","view_locally","tools","edit_text","annotate","add_text",
        "print_pdf","sign","tap_to_add_text"]
T = {
"ar": ["التقاط صورة","اختيار من المعرض","اختر طريقة القص","يمكنك تغييرها في أي وقت من \"إعدادات المسح\".","قص تلقائي","بدون قص","لا تسأل مرة أخرى","إعدادات المسح","يلزم إذن الكاميرا لالتقاط الصور","تعذر التقاط الصورة، حاول مرة أخرى","إعادة الالتقاط","قص","يسار","يمين","تطبيق على الكل","لم يتم العثور على حواف المستند","جارٍ المعالجة… (%d%%)","إضافة صفحات","تم التحويل بنجاح!","عرض محليًا","الأدوات","تعديل النص","تعليق توضيحي","إضافة نص","طباعة PDF","توقيع","اضغط على الصفحة لكتابة نص"],
"de": ["Foto aufnehmen","Aus Galerie wählen","Zuschneidemethode wählen","Du kannst dies jederzeit in den \"Scan-Einstellungen\" ändern.","Automatisch zuschneiden","Nicht zuschneiden","Nicht mehr fragen","Scan-Einstellungen","Kameraberechtigung wird für Fotos benötigt","Foto konnte nicht aufgenommen werden, bitte erneut versuchen","Neu aufnehmen","Zuschneiden","Links","Rechts","Auf alle anwenden","Keine Dokumentkanten gefunden","Wird verarbeitet… (%d%%)","Seiten hinzufügen","Erfolgreich konvertiert!","Lokal ansehen","Werkzeuge","Text bearbeiten","Markieren","Text hinzufügen","PDF drucken","Unterschreiben","Tippe auf die Seite, um Text einzugeben"],
"es": ["Tomar una foto","Elegir de la galería","Elige el método de recorte","Puedes cambiarlo cuando quieras en \"Ajustes de escaneo\".","Recorte automático","Sin recorte","No volver a preguntar","Ajustes de escaneo","Se necesita permiso de cámara para tomar fotos","No se pudo tomar la foto, inténtalo de nuevo","Repetir","Recortar","Izquierda","Derecha","Aplicar a todas","No se encontraron bordes del documento","Procesando… (%d%%)","Añadir páginas","¡Convertido correctamente!","Ver en el dispositivo","Herramientas","Editar texto","Anotar","Añadir texto","Imprimir PDF","Firmar","Toca la página para escribir texto"],
"fa": ["گرفتن عکس","انتخاب از گالری","روش برش را انتخاب کنید","هر زمان می‌توانید آن را در \"تنظیمات اسکن\" تغییر دهید.","برش خودکار","بدون برش","دیگر نپرس","تنظیمات اسکن","برای گرفتن عکس، اجازه دوربین لازم است","عکس گرفته نشد، دوباره تلاش کنید","عکس مجدد","برش","چپ","راست","اعمال روی همه","لبه‌های سند پیدا نشد","در حال پردازش… (%d%%)","افزودن صفحه","با موفقیت تبدیل شد!","مشاهده در دستگاه","ابزارها","ویرایش متن","حاشیه‌نویسی","افزودن متن","چاپ PDF","امضا","برای نوشتن متن روی صفحه ضربه بزنید"],
"fr": ["Prendre une photo","Choisir dans la galerie","Choisir la méthode de recadrage","Vous pouvez la modifier à tout moment dans \"Paramètres de numérisation\".","Recadrage auto","Sans recadrage","Ne plus demander","Paramètres de numérisation","L'autorisation de l'appareil photo est nécessaire","Impossible de prendre la photo, réessayez","Reprendre","Recadrer","Gauche","Droite","Appliquer à tout","Aucun bord de document trouvé","Traitement… (%d%%)","Ajouter des pages","Converti avec succès !","Voir sur l'appareil","Outils","Modifier le texte","Annoter","Ajouter du texte","Imprimer le PDF","Signer","Touchez la page pour saisir du texte"],
"in": ["Ambil foto","Pilih dari galeri","Pilih metode pemotongan","Anda dapat mengubahnya kapan saja di \"Pengaturan pindai\".","Potong otomatis","Tanpa potong","Jangan tanya lagi","Pengaturan pindai","Izin kamera diperlukan untuk mengambil foto","Tidak dapat mengambil foto, coba lagi","Ambil ulang","Potong","Kiri","Kanan","Terapkan ke semua","Tepi dokumen tidak ditemukan","Memproses… (%d%%)","Tambah halaman","Berhasil dikonversi!","Lihat di perangkat","Alat","Edit teks","Anotasi","Tambah teks","Cetak PDF","Tanda tangan","Ketuk halaman untuk mengetik teks"],
"it": ["Scatta una foto","Scegli dalla galleria","Scegli il metodo di ritaglio","Puoi cambiarlo in qualsiasi momento in \"Impostazioni scansione\".","Ritaglio automatico","Nessun ritaglio","Non chiedere più","Impostazioni scansione","Serve l'autorizzazione della fotocamera per scattare foto","Impossibile scattare la foto, riprova","Riscatta","Ritaglia","Sinistra","Destra","Applica a tutte","Nessun bordo del documento trovato","Elaborazione… (%d%%)","Aggiungi pagine","Convertito correttamente!","Visualizza sul dispositivo","Strumenti","Modifica testo","Annota","Aggiungi testo","Stampa PDF","Firma","Tocca la pagina per scrivere il testo"],
"ja": ["写真を撮る","ギャラリーから選択","トリミング方法を選択","「スキャン設定」でいつでも変更できます。","自動トリミング","トリミングなし","今後表示しない","スキャン設定","写真を撮るにはカメラの許可が必要です","写真を撮れませんでした。もう一度お試しください","撮り直す","トリミング","左","右","すべてに適用","文書の端が見つかりません","処理中… (%d%%)","ページを追加","変換しました！","端末で表示","ツール","テキストを編集","注釈","テキストを追加","PDFを印刷","署名","ページをタップしてテキストを入力"],
"ko": ["사진 촬영","갤러리에서 선택","자르기 방법 선택","\"스캔 설정\"에서 언제든지 변경할 수 있습니다.","자동 자르기","자르지 않음","다시 묻지 않기","스캔 설정","사진을 찍으려면 카메라 권한이 필요합니다","사진을 찍지 못했습니다. 다시 시도하세요","다시 촬영","자르기","왼쪽","오른쪽","모두 적용","문서 가장자리를 찾지 못했습니다","처리 중… (%d%%)","페이지 추가","변환되었습니다!","기기에서 보기","도구","텍스트 편집","주석","텍스트 추가","PDF 인쇄","서명","페이지를 탭하여 텍스트 입력"],
"ms": ["Ambil foto","Pilih daripada galeri","Pilih kaedah pemangkasan","Anda boleh menukarnya bila-bila masa dalam \"Tetapan imbas\".","Pangkas auto","Tiada pangkasan","Jangan tanya lagi","Tetapan imbas","Kebenaran kamera diperlukan untuk mengambil foto","Tidak dapat mengambil foto, cuba lagi","Ambil semula","Pangkas","Kiri","Kanan","Guna pada semua","Tepi dokumen tidak ditemui","Memproses… (%d%%)","Tambah halaman","Berjaya ditukar!","Lihat pada peranti","Alatan","Edit teks","Anotasi","Tambah teks","Cetak PDF","Tandatangan","Ketik halaman untuk menaip teks"],
"pt": ["Tirar uma foto","Escolher da galeria","Escolha o método de corte","Você pode alterar a qualquer momento em \"Configurações de digitalização\".","Corte automático","Sem corte","Não perguntar novamente","Configurações de digitalização","É necessária permissão da câmera para tirar fotos","Não foi possível tirar a foto, tente novamente","Refazer","Cortar","Esquerda","Direita","Aplicar a todas","Bordas do documento não encontradas","Processando… (%d%%)","Adicionar páginas","Convertido com sucesso!","Ver no dispositivo","Ferramentas","Editar texto","Anotar","Adicionar texto","Imprimir PDF","Assinar","Toque na página para digitar"],
"ru": ["Сделать фото","Выбрать из галереи","Выберите способ обрезки","Изменить можно в любое время в \"Настройках сканирования\".","Автообрезка","Без обрезки","Больше не спрашивать","Настройки сканирования","Для съёмки нужно разрешение на камеру","Не удалось сделать фото, попробуйте ещё раз","Переснять","Обрезать","Влево","Вправо","Применить ко всем","Края документа не найдены","Обработка… (%d%%)","Добавить страницы","Успешно конвертировано!","Открыть на устройстве","Инструменты","Редактировать текст","Пометки","Добавить текст","Печать PDF","Подписать","Нажмите на страницу, чтобы ввести текст"],
"tr": ["Fotoğraf çek","Galeriden seç","Kırpma yöntemini seçin","Bunu istediğiniz zaman \"Tarama ayarları\"ndan değiştirebilirsiniz.","Otomatik kırp","Kırpma yok","Tekrar sorma","Tarama ayarları","Fotoğraf çekmek için kamera izni gerekli","Fotoğraf çekilemedi, tekrar deneyin","Yeniden çek","Kırp","Sol","Sağ","Tümüne uygula","Belge kenarları bulunamadı","İşleniyor… (%d%%)","Sayfa ekle","Başarıyla dönüştürüldü!","Cihazda görüntüle","Araçlar","Metni düzenle","Not ekle","Metin ekle","PDF yazdır","İmzala","Metin yazmak için sayfaya dokunun"],
"vi": ["Chụp ảnh","Chọn từ thư viện","Chọn cách cắt","Bạn có thể thay đổi bất cứ lúc nào trong \"Cài đặt quét\".","Tự động cắt","Không cắt","Không hỏi lại","Cài đặt quét","Cần quyền máy ảnh để chụp ảnh","Không chụp được ảnh, hãy thử lại","Chụp lại","Cắt","Trái","Phải","Áp dụng cho tất cả","Không tìm thấy cạnh tài liệu","Đang xử lý… (%d%%)","Thêm trang","Chuyển đổi thành công!","Xem trên máy","Công cụ","Sửa văn bản","Chú thích","Thêm văn bản","In PDF","Ký tên","Chạm vào trang để nhập văn bản"],
"uz": ["Suratga olish","Galereyadan tanlash","Kesish usulini tanlang","Buni istalgan vaqtda \"Skanerlash sozlamalari\"da o\\'zgartirishingiz mumkin.","Avto kesish","Kesmaslik","Boshqa so\\'ramaslik","Skanerlash sozlamalari","Suratga olish uchun kamera ruxsati kerak","Surat olinmadi, qayta urinib ko\\'ring","Qayta olish","Kesish","Chap","O\\'ng","Hammasiga qo\\'llash","Hujjat chetlari topilmadi","Ishlanmoqda… (%d%%)","Sahifa qo\\'shish","Muvaffaqiyatli aylantirildi!","Qurilmada ko\\'rish","Asboblar","Matnni tahrirlash","Izoh qo\\'shish","Matn qo\\'shish","PDF chop etish","Imzo","Matn yozish uchun sahifaga bosing"],
"th": ["ถ่ายภาพ","เลือกจากแกลเลอรี","เลือกวิธีครอบตัด","คุณเปลี่ยนได้ทุกเมื่อใน \"การตั้งค่าการสแกน\"","ครอบตัดอัตโนมัติ","ไม่ครอบตัด","ไม่ต้องถามอีก","การตั้งค่าการสแกน","ต้องใช้สิทธิ์กล้องเพื่อถ่ายภาพ","ถ่ายภาพไม่สำเร็จ โปรดลองอีกครั้ง","ถ่ายใหม่","ครอบตัด","ซ้าย","ขวา","ใช้กับทั้งหมด","ไม่พบขอบเอกสาร","กำลังประมวลผล… (%d%%)","เพิ่มหน้า","แปลงสำเร็จ!","ดูในเครื่อง","เครื่องมือ","แก้ไขข้อความ","ใส่คำอธิบาย","เพิ่มข้อความ","พิมพ์ PDF","ลงชื่อ","แตะที่หน้าเพื่อพิมพ์ข้อความ"],
"uk": ["Зробити фото","Вибрати з галереї","Виберіть спосіб обрізання","Змінити можна будь-коли в \"Налаштуваннях сканування\".","Автообрізання","Без обрізання","Більше не питати","Налаштування сканування","Для зйомки потрібен дозвіл на камеру","Не вдалося зробити фото, спробуйте ще раз","Перезняти","Обрізати","Ліворуч","Праворуч","Застосувати до всіх","Краї документа не знайдено","Обробка… (%d%%)","Додати сторінки","Успішно конвертовано!","Відкрити на пристрої","Інструменти","Редагувати текст","Позначки","Додати текст","Друк PDF","Підписати","Торкніться сторінки, щоб ввести текст"],
"pl": ["Zrób zdjęcie","Wybierz z galerii","Wybierz metodę kadrowania","Możesz to zmienić w dowolnej chwili w \"Ustawieniach skanowania\".","Automatyczne kadrowanie","Bez kadrowania","Nie pytaj ponownie","Ustawienia skanowania","Do robienia zdjęć potrzebne jest uprawnienie aparatu","Nie udało się zrobić zdjęcia, spróbuj ponownie","Powtórz","Kadruj","W lewo","W prawo","Zastosuj do wszystkich","Nie znaleziono krawędzi dokumentu","Przetwarzanie… (%d%%)","Dodaj strony","Przekonwertowano!","Pokaż na urządzeniu","Narzędzia","Edytuj tekst","Adnotacje","Dodaj tekst","Drukuj PDF","Podpisz","Dotknij strony, aby wpisać tekst"],
"tl": ["Kumuha ng litrato","Pumili mula sa gallery","Pumili ng paraan ng pag-crop","Mababago mo ito anumang oras sa \"Scan settings\".","Auto crop","Walang crop","Huwag nang itanong","Scan settings","Kailangan ang pahintulot sa camera para kumuha ng litrato","Hindi nakuha ang litrato, subukang muli","Kunan muli","I-crop","Kaliwa","Kanan","Ilapat sa lahat","Walang nakitang gilid ng dokumento","Pinoproseso… (%d%%)","Magdagdag ng pahina","Matagumpay na na-convert!","Tingnan sa device","Mga tool","I-edit ang text","Mag-annotate","Magdagdag ng text","I-print ang PDF","Pumirma","I-tap ang pahina para mag-type"],
"zh-rTW": ["拍照","從相簿選擇","選擇裁切方式","你可以隨時在「掃描設定」中調整。","自動裁切","不裁切","不再詢問","掃描設定","拍照需要相機權限","無法拍照，請再試一次","重拍","裁切","向左","向右","全部套用","找不到文件邊緣","處理中… (%d%%)","新增頁面","轉換成功！","在本機檢視","工具","編輯文字","註解","新增文字","列印 PDF","簽名","點一下頁面以輸入文字"],
"ur": ["تصویر لیں","گیلری سے منتخب کریں","کاٹنے کا طریقہ منتخب کریں","آپ اسے کسی بھی وقت \"اسکین سیٹنگز\" میں بدل سکتے ہیں۔","خودکار کٹائی","کٹائی نہیں","دوبارہ نہ پوچھیں","اسکین سیٹنگز","تصویر لینے کے لیے کیمرے کی اجازت درکار ہے","تصویر نہیں لی جا سکی، دوبارہ کوشش کریں","دوبارہ لیں","کاٹیں","بائیں","دائیں","سب پر لاگو کریں","دستاویز کے کنارے نہیں ملے","پروسیسنگ… (%d%%)","صفحات شامل کریں","کامیابی سے تبدیل ہو گیا!","ڈیوائس میں دیکھیں","ٹولز","متن میں ترمیم","نشان لگائیں","متن شامل کریں","PDF پرنٹ کریں","دستخط","متن لکھنے کے لیے صفحے پر ٹیپ کریں"],
"zh-rCN": ["拍照","从相册选择","选择裁剪方式","你可以随时在“扫描设置”中调整。","自动裁剪","不裁剪","不再询问","扫描设置","拍照需要相机权限","无法拍照，请重试","重拍","裁剪","向左","向右","全部应用","未找到文档边缘","处理中… (%d%%)","添加页面","转换成功！","在本地查看","工具","编辑文字","批注","添加文字","打印 PDF","签名","点按页面以输入文字"],
}
def esc(s):
    out = s.replace("\\'", "\u0000").replace("'", "\\'").replace('"', '\\"')
    return out.replace("\u0000", "\\'")
for loc, vals in T.items():
    assert len(vals) == len(KEYS), (loc, len(vals))
    p = f"app/src/main/res/values-{loc}/strings.xml"
    s = open(p, encoding="utf-8").read()
    s = re.sub(r"\n    <!-- step6 -->.*?<!-- /step6 -->", "", s, flags=re.S)
    block = "\n    <!-- step6 -->\n" + "".join(f'    <string name="{k}">{esc(v)}</string>\n' for k, v in zip(KEYS, vals)) + "    <!-- /step6 -->"
    s = s.replace("\n</resources>", block + "\n</resources>")
    open(p, "w", encoding="utf-8").write(s)
print("step6 translations:", len(T))
