# -*- coding: utf-8 -*-
"""Appends step-2 strings (All files screen) to values-XX/strings.xml. Run from project root after gen_translations.py."""
import re
KEYS = ["all_files_title","selected_count","search_for_files","cancel","filter_by","sort_name","sort_date_short","file_size",
        "ascending","descending","share","rename","to_home_screen","delete","storage_path","last_modified","recycle_title",
        "recycle_message","move_to_recycle_bin","delete_directly","permission_required","rate_subtitle","rate_best","rate"]
T = {
"ar": ["كل الملفات","تم تحديد %d","البحث عن ملفات…","إلغاء","تصفية حسب","الاسم","التاريخ","حجم الملف","تصاعدي","تنازلي","مشاركة","إعادة تسمية","إلى الشاشة\\nالرئيسية","حذف","مسار التخزين","آخر تعديل","نقل إلى سلة المحذوفات أم حذف؟","يمكن استعادة الملفات في سلة المحذوفات خلال 30 يومًا.","نقل إلى سلة المحذوفات","حذف مباشرة","الإذن مطلوب","تقييمك يعني لنا الكثير!","أفضل ما نطمح إليه","تقييم"],
"de": ["Alle Dateien","%d ausgewählt","Dateien suchen…","Abbrechen","Filtern nach","Name","Datum","Dateigröße","Aufsteigend","Absteigend","Teilen","Umbenennen","Zum\\nStartbildschirm","Löschen","Speicherpfad","Zuletzt geändert","In den Papierkorb verschieben oder löschen?","Dateien im Papierkorb können innerhalb von 30 Tagen wiederhergestellt werden.","In den Papierkorb","Direkt löschen","Berechtigung erforderlich","Deine Bewertung bedeutet uns viel!","Das Beste, was wir bekommen können","Bewerten"],
"es": ["Todos los archivos","%d seleccionados","Buscar archivos…","Cancelar","Filtrar por","Nombre","Fecha","Tamaño","Ascendente","Descendente","Compartir","Renombrar","A pantalla\\nde inicio","Eliminar","Ruta de almacenamiento","Última modificación","¿Mover a la papelera o eliminar?","Los archivos de la papelera se pueden restaurar en 30 días.","Mover a la papelera","Eliminar directamente","Permiso necesario","¡Tu valoración significa mucho para nosotros!","Lo mejor que podemos recibir","Valorar"],
"fa": ["همه فایل‌ها","%d انتخاب شد","جستجوی فایل‌ها…","لغو","فیلتر بر اساس","نام","تاریخ","اندازه فایل","صعودی","نزولی","اشتراک‌گذاری","تغییر نام","به صفحه\\nاصلی","حذف","مسیر ذخیره","آخرین تغییر","انتقال به سطل بازیافت یا حذف؟","فایل‌های سطل بازیافت تا ۳۰ روز قابل بازیابی هستند.","انتقال به سطل بازیافت","حذف مستقیم","مجوز لازم است","امتیاز شما برای ما بسیار ارزشمند است!","بهترین امتیاز ممکن","امتیاز دادن"],
"fr": ["Tous les fichiers","%d sélectionné(s)","Rechercher des fichiers…","Annuler","Filtrer par","Nom","Date","Taille","Croissant","Décroissant","Partager","Renommer","Écran\\nd'accueil","Supprimer","Chemin de stockage","Dernière modification","Déplacer vers la corbeille ou supprimer ?","Les fichiers de la corbeille peuvent être restaurés pendant 30 jours.","Déplacer vers la corbeille","Supprimer directement","Autorisation requise","Votre note compte beaucoup pour nous !","Le mieux qu'on puisse avoir","Noter"],
"in": ["Semua file","%d dipilih","Cari file…","Batal","Filter menurut","Nama","Tanggal","Ukuran file","Naik","Turun","Bagikan","Ganti nama","Ke layar\\nutama","Hapus","Lokasi penyimpanan","Terakhir diubah","Pindahkan ke sampah atau hapus?","File di sampah dapat dipulihkan dalam 30 hari.","Pindahkan ke sampah","Hapus langsung","Izin diperlukan","Penilaian Anda sangat berarti bagi kami!","Nilai terbaik untuk kami","Beri nilai"],
"it": ["Tutti i file","%d selezionati","Cerca file…","Annulla","Filtra per","Nome","Data","Dimensione","Crescente","Decrescente","Condividi","Rinomina","Alla schermata\\nHome","Elimina","Percorso","Ultima modifica","Spostare nel cestino o eliminare?","I file nel cestino possono essere ripristinati entro 30 giorni.","Sposta nel cestino","Elimina direttamente","Autorizzazione richiesta","La tua valutazione è importante per noi!","Il massimo che possiamo ricevere","Valuta"],
"ja": ["すべてのファイル","%d 件選択中","ファイルを検索…","キャンセル","並べ替え","名前","日付","ファイルサイズ","昇順","降順","共有","名前を変更","ホーム画面\\nに追加","削除","保存場所","最終更新","ごみ箱に移動しますか、削除しますか？","ごみ箱のファイルは30日以内であれば復元できます。","ごみ箱に移動","完全に削除","権限が必要です","あなたの評価は私たちの励みです！","最高の評価","評価する"],
"ko": ["모든 파일","%d개 선택됨","파일 검색…","취소","정렬 기준","이름","날짜","파일 크기","오름차순","내림차순","공유","이름 변경","홈 화면에\\n추가","삭제","저장 경로","마지막 수정","휴지통으로 이동하거나 삭제할까요?","휴지통의 파일은 30일 이내에 복원할 수 있습니다.","휴지통으로 이동","바로 삭제","권한 필요","여러분의 평가는 큰 힘이 됩니다!","최고의 평가","평가하기"],
"ms": ["Semua fail","%d dipilih","Cari fail…","Batal","Tapis mengikut","Nama","Tarikh","Saiz fail","Menaik","Menurun","Kongsi","Namakan semula","Ke skrin\\nutama","Padam","Laluan storan","Diubah suai terakhir","Alih ke tong kitar semula atau padam?","Fail dalam tong kitar semula boleh dipulihkan dalam 30 hari.","Alih ke tong kitar semula","Padam terus","Kebenaran diperlukan","Penilaian anda amat bermakna!","Yang terbaik untuk kami","Nilai"],
"pt": ["Todos os arquivos","%d selecionados","Pesquisar arquivos…","Cancelar","Filtrar por","Nome","Data","Tamanho","Crescente","Decrescente","Compartilhar","Renomear","Para a tela\\ninicial","Excluir","Local de armazenamento","Última modificação","Mover para a lixeira ou excluir?","Os arquivos da lixeira podem ser restaurados em até 30 dias.","Mover para a lixeira","Excluir diretamente","Permissão necessária","Sua avaliação significa muito para nós!","O melhor que podemos receber","Avaliar"],
"ru": ["Все файлы","Выбрано: %d","Поиск файлов…","Отмена","Сортировать по","Имя","Дата","Размер","По возрастанию","По убыванию","Поделиться","Переименовать","На главный\\nэкран","Удалить","Путь","Изменён","Переместить в корзину или удалить?","Файлы в корзине можно восстановить в течение 30 дней.","В корзину","Удалить сразу","Требуется разрешение","Ваша оценка очень важна для нас!","Лучшая оценка","Оценить"],
"tr": ["Tüm dosyalar","%d seçildi","Dosya ara…","İptal","Sıralama ölçütü","Ad","Tarih","Dosya boyutu","Artan","Azalan","Paylaş","Yeniden adlandır","Ana ekrana\\nekle","Sil","Depolama yolu","Son değişiklik","Geri dönüşüm kutusuna taşınsın mı, silinsin mi?","Geri dönüşüm kutusundaki dosyalar 30 gün içinde geri yüklenebilir.","Geri dönüşüm kutusuna taşı","Doğrudan sil","İzin gerekli","Puanınız bizim için çok değerli!","Alabileceğimiz en iyisi","Puan ver"],
"vi": ["Tất cả tệp","Đã chọn %d","Tìm kiếm tệp…","Hủy","Lọc theo","Tên","Ngày","Kích thước","Tăng dần","Giảm dần","Chia sẻ","Đổi tên","Ra màn hình\\nchính","Xóa","Đường dẫn","Sửa đổi lần cuối","Chuyển vào thùng rác hay xóa?","Tệp trong thùng rác có thể khôi phục trong 30 ngày.","Chuyển vào thùng rác","Xóa trực tiếp","Cần cấp quyền","Đánh giá của bạn rất ý nghĩa với chúng tôi!","Điều tuyệt nhất chúng tôi có thể nhận","Đánh giá"],
"uz": ["Barcha fayllar","%d ta tanlandi","Fayllarni qidirish…","Bekor qilish","Saralash","Nomi","Sana","Fayl hajmi","O\\'sish bo\\'yicha","Kamayish bo\\'yicha","Ulashish","Nomini o\\'zgartirish","Bosh\\nekranga","O\\'chirish","Saqlash yo\\'li","Oxirgi o\\'zgarish","Savatga o\\'tkazilsinmi yoki o\\'chirilsinmi?","Savatdagi fayllarni 30 kun ichida tiklash mumkin.","Savatga o\\'tkazish","To\\'g\\'ridan-to\\'g\\'ri o\\'chirish","Ruxsat kerak","Bahoyingiz biz uchun muhim!","Eng yaxshi baho","Baholash"],
"th": ["ไฟล์ทั้งหมด","เลือกแล้ว %d","ค้นหาไฟล์…","ยกเลิก","กรองตาม","ชื่อ","วันที่","ขนาดไฟล์","น้อยไปมาก","มากไปน้อย","แชร์","เปลี่ยนชื่อ","ไปที่หน้า\\nจอหลัก","ลบ","ตำแหน่งจัดเก็บ","แก้ไขล่าสุด","ย้ายไปถังขยะหรือลบ?","ไฟล์ในถังขยะสามารถกู้คืนได้ภายใน 30 วัน","ย้ายไปถังขยะ","ลบทันที","ต้องได้รับอนุญาต","คะแนนของคุณมีความหมายกับเรามาก!","คะแนนที่ดีที่สุด","ให้คะแนน"],
"uk": ["Усі файли","Вибрано: %d","Пошук файлів…","Скасувати","Сортувати за","Назва","Дата","Розмір","За зростанням","За спаданням","Поділитися","Перейменувати","На головний\\nекран","Видалити","Шлях","Змінено","Перемістити в кошик чи видалити?","Файли з кошика можна відновити протягом 30 днів.","У кошик","Видалити одразу","Потрібен дозвіл","Ваша оцінка дуже важлива для нас!","Найкраща оцінка","Оцінити"],
"pl": ["Wszystkie pliki","Wybrano: %d","Szukaj plików…","Anuluj","Sortuj według","Nazwa","Data","Rozmiar","Rosnąco","Malejąco","Udostępnij","Zmień nazwę","Na ekran\\ngłówny","Usuń","Ścieżka","Ostatnia zmiana","Przenieść do kosza czy usunąć?","Pliki w koszu można przywrócić w ciągu 30 dni.","Przenieś do kosza","Usuń od razu","Wymagane uprawnienie","Twoja ocena wiele dla nas znaczy!","Najlepsza ocena","Oceń"],
"tl": ["Lahat ng file","%d ang napili","Maghanap ng file…","Kanselahin","I-filter ayon sa","Pangalan","Petsa","Laki ng file","Pataas","Pababa","Ibahagi","Palitan ang pangalan","Sa home\\nscreen","Burahin","Lokasyon","Huling binago","Ilipat sa recycle bin o burahin?","Maibabalik ang mga file sa recycle bin sa loob ng 30 araw.","Ilipat sa recycle bin","Burahin agad","Kailangan ng pahintulot","Malaking bagay sa amin ang iyong rating!","Ang pinakamagandang makukuha namin","I-rate"],
"zh-rTW": ["所有檔案","已選取 %d 個","搜尋檔案…","取消","排序方式","名稱","日期","檔案大小","遞增","遞減","分享","重新命名","加到\\n主畫面","刪除","儲存路徑","上次修改","移至資源回收筒或直接刪除？","資源回收筒中的檔案可在 30 天內還原。","移至資源回收筒","直接刪除","需要權限","您的評分對我們意義重大！","我們能得到的最佳評價","評分"],
"ur": ["تمام فائلیں","%d منتخب","فائلیں تلاش کریں…","منسوخ کریں","فلٹر بلحاظ","نام","تاریخ","فائل کا سائز","صعودی","نزولی","شیئر کریں","نام تبدیل کریں","ہوم اسکرین\\nپر","حذف کریں","اسٹوریج پاتھ","آخری ترمیم","ری سائیکل بن میں منتقل کریں یا حذف کریں؟","ری سائیکل بن کی فائلیں 30 دن کے اندر بحال کی جا سکتی ہیں۔","ری سائیکل بن میں منتقل کریں","براہ راست حذف کریں","اجازت درکار ہے","آپ کی ریٹنگ ہمارے لیے بہت اہم ہے!","بہترین جو ہمیں مل سکتا ہے","ریٹ کریں"],
"zh-rCN": ["所有文件","已选择 %d 项","搜索文件…","取消","排序方式","名称","日期","文件大小","升序","降序","分享","重命名","添加到\\n主屏幕","删除","存储路径","最后修改","移至回收站还是直接删除？","回收站中的文件可在 30 天内恢复。","移至回收站","直接删除","需要权限","您的评分对我们意义重大！","我们能得到的最好评价","评分"],
}
def esc(s):
    out = s.replace("\\'", "\u0000").replace("'", "\\'").replace('"', '\\"')
    return out.replace("\u0000", "\\'")
for loc, vals in T.items():
    assert len(vals) == len(KEYS), (loc, len(vals))
    p = f"app/src/main/res/values-{loc}/strings.xml"
    s = open(p, encoding="utf-8").read()
    s = re.sub(r"\n    <!-- step2 -->.*?<!-- /step2 -->", "", s, flags=re.S)
    block = "\n    <!-- step2 -->\n" + "".join(f'    <string name="{k}">{esc(v)}</string>\n' for k, v in zip(KEYS, vals)) + "    <!-- /step2 -->"
    s = s.replace("\n</resources>", block + "\n</resources>")
    open(p, "w", encoding="utf-8").write(s)
print("step2 translations:", len(T))
